### PR TITLE
Ignore build directories and fix minor issue in MANIFEST.

### PR DESCRIPTION
**Pull request by eeshangarg**
@timabbott: This is related to #53, should we make a new release with this fix or should we include it in the current release and re-upload the source distribution? :)

### CODE REVIEW

**Comment by timabbott** [comment]
I would just post a new release; it's almost never a good idea to try to change the meaning of an existing released version.

**Comment by SEAPUNK** [comment]
Hi, I'd like to know when a release has been updated or posted. Will this PR be updated with that status?

**Comment by eeshangarg** [comment]
@SEAPUNK: Just made a new release! :)

**Comment by SEAPUNK** [comment]
Thanks!

**Pull request merged**
