### PR TITLE
Add python3.7 support and remove forgetten 3.3 parts

### PR DESCRIPTION
**Pull request by usta**
In general just fixes test configs and setup.py , trivial changes

### CODE REVIEW

**Comment by timabbott** [comment]
@usta thanks for the contribution.  Can you figure our the CI failure?

**Comment by usta** [comment]
@timabbott It was a problem about travisCI without using xenial and sudo rights python 3.7 CI couldn't work. ( Python 3.7 requires OpenSSL 1.0.2+ and only xenial have that version )
So until xenial became default we have 2 options : 
1- whether we need to especially run 3.7 tests on xenial others on trusty  (just like right now )
2- OR I will change it to run all tests ( 2.7 , 3.4 , 3.5 , 3,6 , 3.7 ) will run on xenial

**Comment by timabbott** [comment]
I think it'd be reasonable to just upgrade to Xenial for CI, since Trusty will be EOL soon.

**Comment by usta** [comment]
@timabbott  so this PR done these things :
* Move CI system to Xenial that will enable us to test 3.7 and others together and much recent platform
* Adds py 3.7 support for setup.py
* Adds py37 env into tox.ini
* Removes 3.3 and adds 3.6 and 3.7 versions into test/__init__.py

**Comment by timabbott** [comment]
Merged as the commits ending with e49954e4f049e0844896bdfda4401f07eba921c6, thanks @usta!

**Comment by timabbott** [comment]
@eeshangarg can you do a release to offer 3.7 support soon?

**Pull request closed without merging**
