### PR TITLE
Add travis conf

### LINKED ISSUE #30: Get Travis CI working
This repo is signed up for Travis CI, but doesn't have a working .travis.yml file.

### PR DESCRIPTION
**Pull request by umairwaheed**
Fixes #30.

### CODE REVIEW

**Comment by timabbott** [comment]
Looks list tests don't pass quite yet?

**Comment by umairwaheed** [comment]
Yeah. Will probably have to test this more.

**Comment by umairwaheed** [comment]
@timabbott, ready for review.

**Comment by timabbott** [comment]
Looks great, merged, thanks @umairwaheed!

**Pull request merged**
